test: fix removeUser unauth testcase
centrifuge/tinlake-proxy pull request #34
Opened 2022-11-18 11:56 UTC by xmxanuel

2022-11-18 12:24 UTC, offerijns approved these changes

2022-11-18 14:53 UTC, AStox requested changes

2022-11-18 14:53 UTC, AStox commented on test/proxy.t.sol
> +        proxy.removeUser(address(this));
Woops! lol you fixed the wrong test.

2022-11-19 11:18 UTC, xmxanuel commented on test/proxy.t.sol
> +        proxy.removeUser(address(this));
fixed

2022-11-19 11:19 UTC, xmxanuel commented
I fixed all the `solc` warnings as well. We still should update the Readme.

2022-11-21 04:41 UTC, AStox approved these changes

2022-11-28 15:30 UTC, merged